name: Build and Deploy Image

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build . -t kzdv/overflight-api:${GITHUB_SHA::6}
      - name: Upload SHA tagged image
        run: docker push kzdv/overflight-api:${GITHUB_SHA::6}
      - name: Set image to latest tag
        run: docker tag kzdv/overflight-api:${GITHUB_SHA::6} kzdv/overflight-api:latest
      - name: Push latest Image
        run: docker push kzdv/overflight-api:latest
      - name: Deploy image to cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECTL }}
          TAG: ${{ GITHUB_SHA::6 }}
        with:
          args: set image deployment/overflight-api overflight-api=kzdv/overflight-api:$TAG -n prod
